### ISSUE TITLE
Did you ever succeed?

### ISSUE THREAD

**Issue by nixinator** [jreidinger/trophy-clanlib2#1]
Dod you ever managed to get this going?

I'm trying to get super methane brother to compile on a later version of clanlib.

however, it may be impossible!

**Comment by jreidinger** [comment]
@nixinator Hi, I get to state that it runs a graphic, but then due to not enough time give up.

**Comment by nixinator** [comment]
more and more software is getting to the point where it can no longer be compiled from source, as updates and ecosystems move faster and faster, i can only see this getting worse and the only options is to run a binary under some kind of virtual machine emulation. closing.
